### ISSUE TITLE
Missing description of Capacity enchantment

### ISSUE THREAD

**Issue by ikon106** [Rouesvm/Backpacks-Polymer#10]
I can't find a description of what the capacity enchantment does in any documentation. Would you please add it to some place?

**Comment by Rouesvm** [comment]
Added the enchantment's info to the mod's modrinth page, if it's good enough close this issue.

**Comment by ikon106** [comment]
Perfect! Thank you! If I understand correctly it adds 9 slots per level of the enchantment?

**Comment by Rouesvm** [comment]
Yes.
