### ISSUE TITLE
[BUG] Can't open when clicking on block

### ISSUE THREAD

**Issue by ikon106** [Rouesvm/Backpacks-Polymer#4]
**Describe the bug**
We can only open the backpack when right-clicking with it in the air.

**To Reproduce**
1. Right-click with backpack on block.

**Expected behavior**
The backpack should open even when clicked on a block.

**Additional context**
Playing on a fabric server with polymer installed.

**Comment by Rouesvm** [comment]
Should be fixed in the latest release

**Comment by ikon106** [comment]
It is, thanks!
