### ISSUE TITLE
[BUG] Item Deletion/Duplication Glitch

### ISSUE THREAD

**Issue by cecaelion** [Rouesvm/Backpacks-Polymer#5]
**Describe the bug**
Items being placed in a backpack or removed from a backpack are, respectively, deleted or duplicated after picking up the backpack.

**To Reproduce**
1. Get a backpack and two distinct items.
2. Place item 2 in the backpack and close it normally.
3. Open the backpack. Take item 2 out and put item 1 in. Do not close the backpack yet.
4. Pick up the backpack. (The backpack GUI will close on its own.)
5. Open the backpack. Item 1 will be gone and item 2 will be in both the backpack and your inventory.

**Expected behavior**
Trying to pick up the backpack when in its GUI should not allow you to pick up the backpack, but also shouldn't close the GUI without saving the backpack's contents.

**Provide a log file**
Nothing occurs in the log when this happens.

**Additional context**
First noticed on a server, but this also occurs in isolation. Minecraft version is 1.21, mod version is 1.1.1.

**Comment by Rouesvm** [comment]
Should be fixed in the latest release, version 1.1.2 of 1.21
