### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by salmoooon** [Rouesvm/Backpacks-Polymer#7]
1. Different icons for small, medium, and large backpacks.
  - So it's easier to distinguish among the three.
2. Change the recipe of the enderpack from requiring a small backpack to a large one.
  - Enderpacks and global packs are too powerful in-game for how much they cost.
  - Enderpack being an ender chest that doesn't need to be placed and thus won't break when being mined.
  - Globalpack can literally transfer items between players million blocks away

**Comment by Rouesvm** [comment]
Thanks for the suggestion. 
Understandable, I will do both of these.
